'use client'

import mermaid from 'mermaid'
import { useEffect, useRef, useState } from 'react'
import { Loader2 } from 'lucide-react'

export function MermaidDiagram({ chart }: { chart: string }) {
    const ref = useRef<HTMLDivElement>(null)
    const [svg, setSvg] = useState<string>('')
    const [error, setError] = useState<boolean>(false)

    useEffect(() => {
        mermaid.initialize({
            startOnLoad: false,
            theme: 'dark',
            securityLevel: 'loose',
            fontFamily: 'inherit',
            suppressErrorRendering: true, // Attempt to suppress default error UI
        })
        mermaid.parseError = (err) => {
            // Suppress console error to avoid clutter, or just log clearly
            // console.warn("Mermaid Parse Error Suppressed:", err) 
        }
    }, [])

    useEffect(() => {
        const renderChart = async () => {
            if (!chart) return

            // Aggressive sanitization: quote ALL unquoted labels and escape inner quotes
            let sanitizedChart = chart.trim()

            // 1. Remove markdown wrappers if the AI accidentally included them
            sanitizedChart = sanitizedChart.replace(/^```mermaid\n?/, '').replace(/\n?```$/, '')

            // 2. Wrap all label contents in quotes if they aren't already, and escape internal quotes
            // This handles id[Label], id{Label}, id(Label)
            sanitizedChart = sanitizedChart
                // Pass 1: Quote unquoted labels (same as before)
                .replace(/\[(?!"|#)([^\]\n]+)\]/g, (_, p1) => `["${p1.replace(/"/g, "'").replace(/\n/g, "<br/>")}"]`)
                .replace(/\{(?!"|#)([^}\n]+)\}/g, (_, p1) => `{"${p1.replace(/"/g, "'").replace(/\n/g, "<br/>")} "}`)
                .replace(/\((?!"|#)([^)\n]+)\)/g, (_, p1) => `("${p1.replace(/"/g, "'").replace(/\n/g, "<br/>")}")`)

            // Pass 2: Fix NESTED quotes in already quoted labels (Critical for 2.5-flash)
            // Finds id["... " ..."] and escapes the internal quotes
            sanitizedChart = sanitizedChart.replace(/\["([^"]*)"\]/g, (match, content) => {
                // Check if the content actually contains quotes that might refer to internal structure
                // This primitive check avoids doing anything if it looks clean
                // But since regex matched balanced quotes, 'content' should be clean?
                // NO, regex `[^"]*` stops at first quote.
                // If original string is `["Text "Quote" Text"]`
                // Regex matches `["Text ` and stops.
                // This is why standard regex fails on nested quotes.
                return match;
            })

            // Force fix for the specific broken pattern generated by AI: `["Text ("Quote")"]`
            // The AI often generates: `id["Database ("Stored Data")"]`
            // Mermaid sees `id["Database ("` ... parser error.
            // We use a specific replacement for this common pattern:
            sanitizedChart = sanitizedChart
                .replace(/\["([^"]*)\("([^"]*)"\)([^"]*)"\]/g, '["$1(\'$2\')$3"]') // Fixes ("...") inside ["..."]
                .replace(/\["([^"]*)"([^"]*)"([^"]*)"\]/g, '["$1\'$2\'$3"]')       // Fixes "..." inside ["..."]

            try {
                const id = `mermaid-${Math.random().toString(36).substr(2, 9)}`
                // Configure strictly to prevent error injection into DOM
                mermaid.parseError = (err) => {
                    console.error("Mermaid Parse Error:", err)
                    setError(true)
                }
                const { svg } = await mermaid.render(id, sanitizedChart)
                setSvg(svg)
                setError(false)
            } catch (err) {
                console.error("Mermaid Render Error:", err)
                setError(true)
            }
        }

        renderChart()
    }, [chart])

    if (error) return null
    if (!svg) return <div className="h-40 flex items-center justify-center text-zinc-500"><Loader2 className="w-5 h-5 animate-spin mr-2" /> Rendering Chart...</div>

    return (
        <div
            ref={ref}
            className="w-full overflow-x-auto p-4 bg-zinc-900/50 rounded-lg border border-white/5 flex justify-center"
            dangerouslySetInnerHTML={{ __html: svg }}
        />
    )
}
